### ISSUE TITLE
parallel test

### ISSUE THREAD

**Issue by jshipton** [firedrakeproject/dcore#26]
I am having trouble running in parallel so I thought I'd make a test. Annoyingly the test works.

1) I have added the parallel testing as we did for the slice code but it might not be the best way to do it

2) mpirun -np 2 python examples/dcmip_3-1_linear_advection_triangle_bdfm1.py gives the error:
Traceback (most recent call last):
  File "examples/dcmip_3-1_linear_advection_triangle_bdfm1.py", line 164, in <module>
    stepper.run(t=0, tmax=3600.0)
  File "/home/jshipton/src/dcore/dcore/timeloop.py", line 43, in run
    state.dump()
  File "/home/jshipton/src/dcore/dcore/state.py", line 88, in dump
    state.dump()
  File "/home/jshipton/src/dcore/dcore/state.py", line 88, in dump
    self.dumpfile.write(*funcs)
  File "/home/jshipton/src/firedrake/local/lib/python2.7/site-packages/firedrake/output.py", line 482, in write
    self.dumpfile.write(*funcs)
  File "/home/jshipton/src/firedrake/local/lib/python2.7/site-packages/firedrake/output.py", line 482, in write
    vtu = self._write_vtu(*functions)
    vtu = self._write_vtu(*functions)
  File "/home/jshipton/src/firedrake/local/lib/python2.7/site-packages/firedrake/output.py", line 381, in _write_vtu
  File "/home/jshipton/src/firedrake/local/lib/python2.7/site-packages/firedrake/output.py", line 381, in _write_vtu
    vtu = self._write_single_pvtu(basename, coordinates, *functions)
  File "/home/jshipton/src/firedrake/local/lib/python2.7/site-packages/firedrake/output.py", line 465, in _write_single_pvtu
    vtu = self._write_single_pvtu(basename, coordinates, *functions)
  File "/home/jshipton/src/firedrake/local/lib/python2.7/site-packages/firedrake/output.py", line 465, in _write_single_pvtu
    f.write('<Piece Source="%s" />\n' % (get_vtu_name(basename, rank)))
  File "/home/jshipton/src/firedrake/local/lib/python2.7/site-packages/firedrake/output.py", line 191, in get_vtu_name
    if comm.size == 1:
AttributeError: 'int' object has no attribute 'size'
    f.write('<Piece Source="%s" />\n' % (get_vtu_name(basename, rank)))
  File "/home/jshipton/src/firedrake/local/lib/python2.7/site-packages/firedrake/output.py", line 191, in get_vtu_name
    if comm.size == 1:
AttributeError: 'int' object has no attribute 'size'

**Comment by jshipton** [comment]
See the test_parallel branch for the parallel test.

**Comment by jshipton** [comment]
Oh, can I only assign one of you? Just wanted to make sure you both saw the issue but maybe you get notified anyway... sorry, still getting used to github!

**Comment by wence-** [comment]
Thanks, fixed in firedrakeproject/firedrake#750.

**Comment by miklos1** [comment]
@jshipton: If you want to make sure they see it, just use "@" + github username. For example: @wence-, @colinjcotter.

**Comment by wence-** [comment]
Should be fixed after updating firedrake.
